[runtime]
std_stream_max_bytes = 1000000
reactive_tests = true
output_max_bytes = 8000000
watcher_on_save = "lazy"
auto_reload = "autorun"
on_cell_change = "autorun"
auto_instantiate = false

[language_servers.pylsp]
enable_pylint = false
enable_flake8 = false
enabled = true
enable_pydocstyle = false
enable_mypy = true
enable_ruff = true
enable_pyflakes = false

[package_management]
manager = "uv"

[snippets]
custom_paths = []
include_default_snippets = true

[diagnostics]

[ai]
rules = ""

[experimental]

[server]
browser = "default"
follow_symlink = false

[display]
code_editor_font_size = 14
default_table_page_size = 10
cell_output = "above"
dataframes = "rich"
default_width = "medium"
theme = "dark"

[keymap]
preset = "vim"

[keymap.overrides]

[formatting]
line_length = 79

[save]
autosave = "after_delay"
format_on_save = false
autosave_delay = 1000

[completion]
activate_on_typing = true
copilot = false
